export enum ProductStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  PENDING_UPDATE_REVIEW = 'PENDING_UPDATE_REVIEW',
  PENDING_ARTIST_CONFIRMATION = 'PENDING_ARTIST_CONFIRMATION',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
