[build]
  base = "frontend"
  command = "npm run build"
  publish = ".output"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200 